### ISSUE TITLE
Joor reflect on Android

### ISSUE THREAD

**Issue by ganatrajay** [jOOQ/jOOR#102]
### Expected behavior and actual behavior:
After integration joor , while calling example given on GitHub , it's crashing and said java.tools class not found 
### Versions:

- jOOR:
- Java:

**Comment by lukaseder** [comment]
Thanks for your message. I'm assuming you tried to use the compilation API, which depends on JDK packages. These aren't shipped to Android, so we can't get that to work for you.

I hope this helps

**Comment by ganatrajay** [comment]
Hi,

We are using kotlin android, see if you can help us for this

Thank you

**Comment by lukaseder** [comment]
I don't know what else you expect me to tell you here.
