### ISSUE TITLE
Joor or Jooq for Android 

### ISSUE THREAD

**Issue by ganatrajay** [jOOQ/jOOR#103]
### Expected behavior and actual behavior: i am have integrated below example and gradle in Kotlin android project. 

Supplier<String> supplier = Reflect.compile(
    "com.example.HelloWorld",
    "package com.example;\n" +
    "class HelloWorld implements java.util.function.Supplier<String> {\n" +
    "    public String get() {\n" +
    "        return \"Hello World!\";\n" +
    "    }\n" +
    "}\n").create().get();

// Prints "Hello World!"
System.out.println(supplier.get());

compile group: 'org.jooq', name: 'joor-java-8', version: '0.9.9'

i just needs to execute one method at runtime 

### Steps to reproduce the problem: 

Android kotlin file 

facing missing class called javax.tools.ToosProvider 

### Versions: Android kotlin 1.3.70 

- jOOR: 
- Java:

**Comment by lukaseder** [comment]
I will just copy paste my previous answer from here: https://github.com/jOOQ/jOOR/issues/102:

> Thanks for your message. I'm assuming you tried to use the compilation API, which depends on JDK packages. These aren't shipped to Android, so we can't get that to work for you.
>
> I hope this helps

It does not work. I'm sorry.
