### ISSUE TITLE
Missing contribution guideline and styling guideline

### ISSUE THREAD

**Issue by DevDengChao** [jOOQ/jOOR#112]
### Expected behavior and actual behavior:
Noop

### Steps to reproduce the problem:
Noop

### Versions:

- jOOR: Noop
- Java: Noop

People want to contribute to this project but find out the files are not formatted with IDE's default style (eg: IDEA).
What should they do =-=?

**Comment by lukaseder** [comment]
Thanks a lot for your message.

This project has 4 classes with tens of lines of code. Let's not overengineer things 😉
