### ISSUE TITLE
Compile with lombok Annotation can supported ? 

### ISSUE THREAD

**Issue by angeltping** [jOOQ/jOOR#123]
### Versions:

- jOOR:
- Java:

how config javax.annotation.processing.Processor ?

```
<dependency>
    <groupId>org.projectlombok</groupId>
    <artifactId>lombok</artifactId>
    <version>1.18.24</version>
</dependency>
```

```
import lombok.Data;

@Data
public class Department {
	private String name;
}
```

**Comment by lukaseder** [comment]
As far as I know, Lombok isn't just an annotation processor, but a compiler plugin, in case of which I doubt it would work out of the box.

However, I'm not sure. You'll have to try it out. Note that jOOR just wraps the JDK's own `JavaCompiler`, simplifying the API, without adding any functionality.
