### ISSUE TITLE
Add license file to the repository

### ISSUE THREAD

**Issue by mnn** [jOOQ/jOOR#17]
I would recommend adding a LICENSE file (or note to README) to this repository. I found on your (old?) Google Code pages that you're releasing under Apache, but I think it should be here on GitHub too.

**Comment by lukaseder** [comment]
Eek, where did it go? I guess it has just never been pushed...

**Comment by lukaseder** [comment]
... ;-) OK, it was in jOOR/jOOR, not at the top level...
