### ISSUE TITLE
Support setting values on final fields

### ISSUE THREAD

**Issue by ooxi** [jOOQ/jOOR#18]
When using jOOR to access `private static` classes or `private final` fields I get an access exception. Therefore I have two questions
1. Why doesn't jOOR automatically try to modify the accessibility?
2. How to modify the accessibility manually? I know of the method [Reflect.accessible](https://github.com/jOOQ/jOOR/blob/master/jOOR/src/main/java/org/joor/Reflect.java#L142) but I don't know how to get field references without using java.lang.reflect

**Comment by lukaseder** [comment]
Thanks for reporting.

> 1. Why doesn't jOOR automatically try to modify the accessibility?

It does, doesn't it?

> 2. How to modify the accessibility manually? I know of the method Reflect.accessible but I don't know how to get field references without using java.lang.reflect

I'm not quite sure if I understand...

**Comment by ooxi** [comment]
I will prepare a test case most likely I made a mistake :)

**Comment by lukaseder** [comment]
No worries :) In any case, we (currently) don't tamper with `final`, although we could

**Comment by ooxi** [comment]
As you had suspected, the problem was not about private but about final. I guess you don't temper with `final` fields because of constant propagation done by the compiler?

**Comment by lukaseder** [comment]
We simply hadn't thought of it / needed it :)

Let's rephrase this issue's title and implement this in a future release

**Comment by lukaseder** [comment]
- For static final fields: http://stackoverflow.com/a/3301720/521799

**Comment by JakubGorski** [comment]
#32

**Comment by lukaseder** [comment]
Implemented with https://github.com/jOOQ/jOOR/pull/32
