### ISSUE TITLE
Latest version on mvn is 0.9.5 ( March 2015)

### ISSUE THREAD

**Issue by jagan-veeraraghavan** [jOOQ/jOOR#30]
I could only March 2015 build of 0.9.5 in mvn. https://mvnrepository.com/artifact/org.jooq/joor .
Is there a plan to push a newer version anytime soon? . The other way for me is to use jOOR as a git submodule and that comes a bit of complications for me

**Comment by lukaseder** [comment]
Sure, why not. Thanks for the reminder. Released this just now. It will be available from Maven Central within the next 1-2 hours.
