### ISSUE TITLE
Java 8 default method support ?

### ISSUE THREAD

**Issue by wenerme** [jOOQ/jOOR#31]
I use joor 0.9.6, doesn't support default method.

```
interface A{
 default void a(){}
}

// Will throw no such method
Reflect.on(new Object()).as(A.class).a()
```

**Comment by lukaseder** [comment]
Thank you very much for your suggestion. This makes sense. Would you be interested in contributing a solution?

**Comment by thomasdarimont** [comment]
In order to properly support and test Java8 Features one needs to split up the build into pre Java 8 and Java 8 sources. Would also be nice if the tests were in the same package as the `Reflect` class as they could then access package protected members.

Java 8 tests could then be guarded with 
```
Assume.assumeTrue(JavaSupport.isJava8orHigher());
```

**Comment by lukaseder** [comment]
@thomasdarimont Interesting solution with the Java 7 / 8 compatibility, thanks for your suggestion. I've commented in the PR

**Comment by thomasdarimont** [comment]
Thanks for review :)

**Comment by lukaseder** [comment]
Hmm, I think I'm going to publish separate artifacts for Java 6 and 8 builds, as in jOOQ. We already have the infrastructure - shouldn't take too long.

**Comment by lukaseder** [comment]
Hmm, the Java 7 compatibility mode is currently not needed...

**Comment by lukaseder** [comment]
Cross releasing implemented with https://github.com/jOOQ/jOOR/issues/36

**Comment by lukaseder** [comment]
Excellent, this now works. Thanks again for your PR, @thomasdarimont

**Comment by lukaseder** [comment]
Gah, @thomasdarimont, do you happen to know how to configure the `.travis.yml` file to run two builds? https://github.com/jOOQ/jOOR/blob/master/.travis.yml

**Comment by lukaseder** [comment]
Nevermind. I think I got it...
