### ISSUE TITLE
Release schedule question

### ISSUE THREAD

**Issue by devinrsmith** [jOOQ/jOOR#80]
Do you have a pre-determined release schedule/diligent in sticking to the milestone issues? I'm hoping to take advantage of https://github.com/jOOQ/jOOR/pull/79 through the official maven central channels. If there aren't plans to push an official release soon, no worries.
Thanks!

**Comment by lukaseder** [comment]
Sure, we can release 0.9.11 with these 3 issues: https://github.com/jOOQ/jOOR/milestone/8?closed=1

Will do today.

**Comment by lukaseder** [comment]
Done. Expect the artifacts to show up on Maven Central within 1-2 hours.
