### ISSUE TITLE
Fields and methods from superclasses are invisible

### ISSUE THREAD

**Issue by iirekm** [jOOQ/jOOR#9]
To finding non-public fields or methods you use code like
```java
    private Method exactMethod(String name, Class<?>[] types) throws NoSuchMethodException {
        final Class<?> type = type();

        // first priority: find a public method with exact signature match in class hierarchy
        try {
            return type.getMethod(name, types);
        }

        // second priority: find a private method with exact signature match on declaring class
        catch (NoSuchMethodException e) {
            return type.getDeclaredMethod(name, types);
        }
    }
```

It's incorrect, it looks for fields/methods only in `type()`, doesn't work if the field/method is in some superclass.

**Comment by Quurks** [comment]
This would be helpful, and the additional traversal cost would only be inflicted if private methods / fields are accessed. For public fields / methods the current, fast implementation is still usable

**Comment by OleksandrKucherenko** [comment]
ok. Thanks! I will try to apply it on each project separately. Give me several minutes for confirmation....

**Comment by OleksandrKucherenko** [comment]
ok. confirming. 

It's actually a bug inside Android Studio. Gradle tree in it shows dependecyUpdate tasks  in wrong place. Gradle command line shows tasks correctly.

**Comment by lukaseder** [comment]
@Quurks / @iirekm : Would you be willing to provide an implementation for this?

**Comment by iirekm** [comment]
I can implement this during this week: I guess that for beginning only the basic version without caching is enough - if a method or field is not present in `type`, try also `type.getSuperclass()` and `type.getInterfaces()`

it can make joor a bit slower, but for me it's OK, joor shouldn't be used for 'everyday' programming but rather for more special tasks, but it shouldn't be that bat, from my experience the slowest part of Java reflection is `member.setAccessible(true)`, which even now isn't cached, finding members is very fast

implementing this feature may make joor a bit backwards incompatible in some rare cases, for example when someone does `try { Reflect.on(...)... } catch(ReflectException e) { ... }`, but I guess those are very, very rare cases, and they can solve this issue using usual techniques like `maven-shade-plugin`

I used joor even in production code a few times, and those 2 issues (maybe a bit slower, and a bit backwards incompatible) totally don't matter for me, and also I guess that won't matter for other users too

**Comment by lukaseder** [comment]
> only the basic version without caching is enough

Yes, I prefer not to add caches early, unless there is really a (measurable) need.

> if a method or field is not present in type, try also type.getSuperclass() and type.getInterfaces()

You don't have to look into the interfaces. They're already covered by the existing logic.

>  for example when someone does try { Reflect.on(...)... } catch(ReflectException e) { ... }

We can live with that. jOOR is 0.9 versioned. This means that we can break compatibility if really needed.

**Comment by iirekm** [comment]
ok i'll do it, this is small change but can be very useful :-)



2015-02-18 11:16 GMT+01:00 Lukas Eder <notifications@github.com>:

**Comment by lukaseder** [comment]
I've merged most of your changes with some minor adaptations. Thanks again for providing your pull request.
