### ISSUE TITLE
Update README version or use placeholder

### ISSUE THREAD

**Issue by thecodewarrior** [jOOQ/jOOR#92]
I was confused initially why `Reflect.compile` wasn't available until I looked further into it and realized that I was using the old version listed in the readme. Currently the readme lists version `0.9.7`, while the latest version is `0.9.12`. If this could be either updated or, for simplicity on updates, replaced with a placeholder like `VERSION`, then others wouldn't run into the same issue in the future.

**Comment by lukaseder** [comment]
Thanks. Fixed: https://github.com/jOOQ/jOOR/commit/ff68bc6fe777eefce381360d753fd0a3f7eefeea
