### ISSUE TITLE
Cannot compile inherited classes

### ISSUE THREAD

**Issue by gabrielps** [jOOQ/jOOR#97]
- jOOR: 1.9.13
- Java: 8

I'm designing a Processor that will generate some test classes. These generated classes will extend an actual non final test class. I'm using jOOR to test the processor.

After a few debug sessions, I was able to determine that the classes are loaded in some kind of order that may not take into account inheritance: https://github.com/jOOQ/jOOR/blob/1e6b04b2086ea0f4341e36753c7b523746f7a3d9/jOOR-java-8/src/main/java/org/joor/Compile.java#L240

**Comment by lukaseder** [comment]
Thank you for your report.

Can you please show an example of what is currently failing? Or even better, a test case.

**Comment by gabrielps** [comment]
It is a duplicate of #81. The subclass was a generated class of the compiled one.
