### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by lburgazzoli** [jOOQ/jOOR#99]
I'm using jOOR to dynamically compile java classes in a Apache Camel subproject (https://github.com/apache/camel-k-runtime) and I'm currently experiencing the issue https://github.com/jOOQ/jOOR/issues/93.

I saw that the issue has been fixed so wonder if there is any chance to get a new release out.

**Comment by lukaseder** [comment]
Thanks for the ping. Yeah, we can probably release this week. There isn't really a strategy here, so any time works. Will update this issue when released.

**Comment by lukaseder** [comment]
I have released 0.9.13. It should be on Maven Central, shortly

**Comment by lburgazzoli** [comment]
Thank you @lukaseder
